config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources 'posts'
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  before_create {self.remember_token = self.create_encrypted_token}
  has_secure_password
  has_many :posts

    def create_encrypted_token
      token = SecureRandom.urlsafe_base64
      Digest::SHA1.hexdigest(token.to_s)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :logged_in?

  def sign_in user
    user.update_attribute(:remember_token, user.create_encrypted_token)
    cookies.permanent[:remember_token] = user.remember_token
    self.current_user = user
  end

  def current_user
    @current_user ||= User.find_by(remember_token: cookies[:remember_token])
  end

  def current_user=(user)
    @current_user = user
  end

  def sign_out
    current_user = nil
    cookies[:remember_token] = nil
  end

  def logged_in?
    !current_user.nil?
  end
  def logged_in_user
    unless logged_in?
      flash[:warning] = "you gotta log in first...."
      redirect_to login_url
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :logged_in_user, only: [:new, :create]

  def new
    @user = current_user
  end

  def create
    @user = current_user
    post = @user.posts.new(text: params[:post][:text])
    if post.save
      flash[:success] = "posted bro"
      redirect_to posts_url
    else
      flash[:danger] = "something broke"
      render 'new'
    end
  end

  def index
    @user = current_user
    @posts = Post.all
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    #find user based on email address on form_for
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      sign_in(user)
      flash[:success] = "sup #{user.name}.. welcome home"
      redirect_to posts_url
    else
      flash.now[:danger] = "NOPE-> TRY AGAIN"
      render 'new'
    end
  end

  def destroy
    sign_out
    flash[:success] = "you're out"
    redirect_to root_url
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MembersOnly</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <a class="navbar-brand" href="/">MEMBERS ONLY</a>
      <nav>
        <ul class="navbar-nav navbar-right navbar main-nav">
          <% if logged_in? %>
            <li><%= @user.name%></li>
            <li><%= link_to "NEW POST", new_post_url%></li>
            <li><%= link_to "log out", logout_url, :method => "delete" %></li>
          <% else %>
            <li><%= link_to "log in", login_url %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </nav>

<div class="container">
  <% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>

  <%= yield %>
</div>

</body>
</html>

app/views/posts/index.html.erb
<ul class="posts">
  <% @posts.each do |post| %>
    <li>
      <div class="left">
        <%= post.text %>
      </div>
      <div class="right">
        <% if logged_in? %>
        | <%= User.find(post.user_id).name %>
        <% end %>
      </div>
    </li>

  <% end %>
</ul>

app/views/posts/new.html.erb
<%= form_for(:post, url: posts_path) do |f| %>
  <%= f.label :text %>
  <%= f.text_field :text %>
  <%= f.submit %>
<% end %>

app/views/static_pages/home.html.erb
<h1>welcome to this lame website</h1>
<% if @user %>
  <h2><%= link_to "SEE POSTS", posts_url %></h2>
  <h2><%= link_to "NEW POST", new_post_url %></h2>
<% else %>
  <h2><%= link_to "LOG IN", login_url %></h2>
  <h2><%= link_to "SEE POSTS", posts_url %></h2>
  <h3>(only logged in users can see post authors)</h3>
<% end %>